/*sql_xml文件配置*/
exports.mapConfig=[
    'daoSQL/chatHandleSQL.xml',
    'daoSQL/coumgSQL.xml',
    'daoSQL/counselorSQL.xml',
    'daoSQL/counselorWorkSQL.xml',
    'daoSQL/openSQL.xml',
    'daoSQL/scheduleSQL.xml',
    'daoSQL/userChatSQL.xml',
    'daoSQL/userSQL.xml'
]